In [1]:
import sys
from pathlib import Path

# Añadir la raíz del proyecto al path
sys.path.append(str(Path.cwd().parent))

from src.storage.minio_client import *

In [2]:
df = read_csv(
    bucket_name="raw",
    object_name="ventas.csv"
)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   IdVenta        100000 non-null  int64
 1   Fecha          100000 non-null  object
 2   Fecha_Entrega  100000 non-null  object
 3   IdCanal        100000 non-null  int64
 4   IdCliente      100000 non-null  int64
 5   IdSucursal     100000 non-null  int64
 6   IdEmpleado     100000 non-null  int64
 7   IdProducto     100000 non-null  int64
 8   Precio         100000 non-null  float64
 9   Cantidad       100000 non-null  int64
dtypes: float64(1), int64(7), object(2)
memory usage: 7.6+ MB

In [4]:
df.describe()

,IdVenta,IdCanal,IdCliente,IdSucursal,IdEmpleado,IdProducto,Precio,Cantidad
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,114999.500000,1.995820,250.723040,10.517500,25.559110,100.435770,251.740860,5.513530
std,28867.657797,0.816045,144.375201,5.776931,14.441795,57.750792,142.585824,2.875983
min,65000.000000,1.000000,1.000000,1.000000,1.000000,1.000000,5.000000,1.000000
25%,89999.750000,1.000000,126.000000,5.000000,13.000000,51.000000,128.360000,3.000000
50%,114999.500000,2.000000,250.000000,11.000000,26.000000,100.000000,251.355000,6.000000
75%,139999.250000,3.000000,376.000000,16.000000,38.000000,151.000000,375.482500,8.000000
max,164999.000000,3.000000,500.000000,20.000000,50.000000,200.000000,500.000000,10.000000

In [6]:
df.shape

(100000, 10)

In [5]:
df.head(50)

,IdVenta,Fecha,Fecha_Entrega,IdCanal,IdCliente,IdSucursal,IdEmpleado,IdProducto,Precio,Cantidad
0,65000,2026-07-08,2026-07-10,3,295,12,36,142,116.75,5
1,65001,2026-07-29,2026-08-04,3,261,18,13,55,123.08,8
2,65002,2026-08-01,2026-08-08,3,309,10,26,53,388.46,1
3,65003,2026-08-05,2026-08-12,2,292,15,21,30,355.18,8
4,65004,2026-07-21,2026-07-27,2,482,3,43,143,53.01,3
5,65005,2026-07-29,2026-08-04,2,307,3,42,87,5.30,9
6,65006,2026-07-19,2026-07-22,3,438,2,14,126,293.66,1
7,65007,2026-07-12,2026-07-18,1,234,4,29,39,14.60,5
8,65008,2026-08-04,2026-08-09,2,320,16,30,64,278.62,3
9,65009,2026-07-11,2026-07-13,1,48,20,21,110,243.76,2
10,65010,2026-07-22,2026-07-28,2,124,6,2,86,101.53,5
11,65011,2026-07-21,2026-07-25,1,466,20,18,50,120.25,4
12,65012,2026-07-31,2026-08-03,2,294,8,2,57,353.05,8
13,65013,2026-07-22,2026-07-29,1,126,9,39,20,487.17,6
14,65014,2026-07-30,2026-07-31,2,445,14,24,65,296.15,6
15,65015,2026-07-17,2026-07-20,1,98,6,23,194,288.95,10
16,65016,2026-07-25,2026-07-26,1,232,2,28,124,280.98,1
17,65017,2026-07-13,2026-07-17,3,439,20,33,56,179.83,9
18,65018,2026-07-25,2026-07-31,3,495,15,30,160,254.20,3
19,65019,2026-08-03,2026-08-06,3,316,14,44,176,188.59,7
20,65020,2026-07-10,2026-07-16,1,480,10,43,38,238.59,9
21,65021,2026-07-10,2026-07-13,2,472,16,1,137,230.47,4
22,65022,2026-07-16,2026-07-19,2,437,15,34,30,347.99,10
23,65023,2026-07-16,2026-07-20,3,425,3,48,137,296.82,10
24,65024,2026-08-05,2026-08-10,1,197,20,29,40,10.71,7
25,65025,2026-07-20,2026-07-25,1,144,14,44,28,242.95,2
26,65026,2026-07-23,2026-07-29,3,454,20,18,44,73.74,5
27,65027,2026-08-04,2026-08-08,3,413,1,13,87,160.91,1
28,65028,2026-07-26,2026-08-02,3,446,1,24,11,261.72,5
29,65029,2026-07-07,2026-07-08,3,215,1,18,91,333.07,4
30,65030,2026-08-05,2026-08-12,3,338,4,28,69,295.43,7
31,65031,2026-08-05,2026-08-06,1,280,16,9,71,267.22,3
32,65032,2026-08-04,2026-08-11,1,20,8,10,57,127.12,8
33,65033,2026-07-30,2026-08-03,1,358,19,20,51,92.40,6
34,65034,2026-07-23,2026-07-27,2,467,6,45,120,317.20,8
35,65035,2026-07-11,2026-07-15,2,424,3,9,169,22.78,5
36,65036,2026-07-07,2026-07-08,3,298,8,16,113,100.61,1
37,65037,2026-07-27,2026-07-28,1,7,4,45,38,143.05,3
38,65038,2026-07-10,2026-07-12,2,377,18,50,64,67.76,7
39,65039,2026-07-12,2026-07-15,1,218,16,43,158,149.89,5
40,65040,2026-07-27,2026-07-29,2,472,7,37,177,24.55,4
41,65041,2026-07-06,2026-07-07,2,349,19,43,63,195.81,3
42,65042,2026-08-05,2026-08-10,3,278,12,37,142,96.69,3
43,65043,2026-07-28,2026-08-04,3,293,8,31,85,474.23,2
44,65044,2026-07-26,2026-07-29,1,461,11,46,173,416.49,9
45,65045,2026-07-14,2026-07-17,2,451,15,14,5,16.84,3
46,65046,2026-07-29,2026-07-31,1,292,14,37,7,205.07,9
47,65047,2026-07-15,2026-07-18,1,314,14,11,100,247.46,4
48,65048,2026-08-03,2026-08-05,3,440,8,42,6,373.38,2
49,65049,2026-07-15,2026-07-19,1,320,4,42,200,376.72,7